version: '3'
services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/html/:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - php
  php:
    image: php:8.1-fpm-alpine
    ports:
     - 9000:9000
    volumes:
      - ./www/html/:/var/www/html/